import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const tooltipStyle = { borderRadius: 12, border: '1px solid #e2e8f0', boxShadow: '0 8px 22px rgba(15, 23, 42, .08)', fontSize: 11, color: '#17231d' }

export function ForecastChart({ data, metric = 'temperature' }: { data: Array<Record<string, any>>; metric?: 'temperature' | 'rainfall' | 'humidity' | 'soil' }) {
  const config = { temperature: { key: 'panchayat_temperature', blockKey: 'block_temperature', color: '#e07b39', unit: '°C', name: 'Panchayat' }, rainfall: { key: 'panchayat_rainfall', blockKey: 'block_rainfall', color: '#3b82c4', unit: ' mm', name: 'Rainfall' }, humidity: { key: 'humidity', blockKey: 'humidity', color: '#7c66bd', unit: '%', name: 'Humidity' }, soil: { key: 'soil_moisture', blockKey: 'soil_moisture', color: '#36a269', unit: '%', name: 'Soil moisture' } }[metric]
  return <ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 8, right: 8, left: -18, bottom: 0 }}><CartesianGrid stroke="#edf2ef" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 10, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 10, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} formatter={(value, name) => [`${Number(value)}${config.unit}`, name === config.blockKey ? 'Block forecast' : 'AI-downscaled']} /><Legend iconType="circle" wrapperStyle={{ fontSize: 10, paddingTop: 8 }} /><Line type="monotone" dataKey={config.blockKey} name="Block" stroke="#a8b6ae" strokeWidth={2} strokeDasharray="5 5" dot={false} /><Line type="monotone" dataKey={config.key} name="Panchayat" stroke={config.color} strokeWidth={3} dot={{ r: 3, fill: config.color, strokeWidth: 0 }} activeDot={{ r: 5 }} /></LineChart></ResponsiveContainer>
}

export function TrendChart({ data, dataKey, color = '#2f8f63', unit = '', name = 'Value', reference }: { data: Array<Record<string, any>>; dataKey: string; color?: string; unit?: string; name?: string; reference?: number }) {
  return <ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><defs><linearGradient id={`gradient-${dataKey}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={0.25} /><stop offset="100%" stopColor={color} stopOpacity={0.01} /></linearGradient></defs><CartesianGrid stroke="#edf2ef" vertical={false} /><XAxis dataKey="date" tickFormatter={(value) => String(value).slice(5)} tick={{ fontSize: 10, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 10, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} formatter={(value) => [`${Number(value)}${unit}`, name]} />{reference !== undefined && <ReferenceLine y={reference} stroke="#f59e0b" strokeDasharray="4 4" />} <Area type="monotone" dataKey={dataKey} stroke={color} strokeWidth={2.5} fill={`url(#gradient-${dataKey})`} /></AreaChart></ResponsiveContainer>
}

export function ActualPredictedChart({ data }: { data: Array<Record<string, any>> }) {
  return <ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 10, right: 12, left: -18, bottom: 0 }}><CartesianGrid stroke="#edf2ef" vertical={false} /><XAxis dataKey="point" tick={{ fontSize: 10, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><YAxis tick={{ fontSize: 10, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} formatter={(value, name) => [Number(value).toFixed(2), name === 'actual' ? 'Observed demo' : 'ML prediction']} /><Legend wrapperStyle={{ fontSize: 10 }} /><Line type="monotone" dataKey="actual" name="Observed" stroke="#17231d" strokeWidth={2.5} dot={{ r: 3, fill: '#17231d' }} /><Line type="monotone" dataKey="predicted" name="ML prediction" stroke="#2f8f63" strokeWidth={2.5} strokeDasharray="5 3" dot={{ r: 3, fill: '#2f8f63' }} /></LineChart></ResponsiveContainer>
}

export function ComparisonBars({ data }: { data: Array<{ label: string; block: number; panchayat: number; unit?: string }> }) {
  return <ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{ top: 4, right: 18, left: 8, bottom: 0 }} barGap={5}><CartesianGrid stroke="#edf2ef" horizontal={false} /><XAxis type="number" tick={{ fontSize: 10, fill: '#94a3b8' }} axisLine={false} tickLine={false} /><YAxis type="category" dataKey="label" width={92} tick={{ fontSize: 10, fill: '#64748b' }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} /><Legend wrapperStyle={{ fontSize: 10 }} /><Bar dataKey="block" name="Block" fill="#cbd5e1" radius={[0, 5, 5, 0]} /><Bar dataKey="panchayat" name="AI Panchayat" fill="#2f8f63" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer>
}

export function MiniSparkline({ data, dataKey, color = '#2f8f63' }: { data: Array<Record<string, any>>; dataKey: string; color?: string }) {
  return <ResponsiveContainer width="100%" height="100%"><LineChart data={data}><Line type="monotone" dataKey={dataKey} stroke={color} strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer>
}
